name: Tests

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test-arch:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run FedericoCarboni/setup-ffmpeg (ARM64)
        uses: ./
        with:
          architecture: arm64

      - run: which ffmpeg
      - run: which ffprobe

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run FedericoCarboni/setup-ffmpeg (default)
        uses: ./

      - run: ffmpeg -version
      - run: ffprobe -version

      - name: Run FedericoCarboni/setup-ffmpeg (Git version)
        uses: ./
        with:
          ffmpeg-version: git

      - run: ffmpeg -version
      - run: ffprobe -version

      - name: Run FedericoCarboni/setup-ffmpeg (specific version 5.1.1)
        uses: ./
        with:
          ffmpeg-version: '5.1.1'

      - run: ffmpeg -version
      - run: ffprobe -version

  test-shared:
    runs-on: windows-latest
    timeout-minutes: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run FedericoCarboni/setup-ffmpeg (6.1.1 shared)
        uses: ./
        with:
          ffmpeg-version: '6.1.1'
          linking-type: shared

      - name: Run FedericoCarboni/setup-ffmpeg (release shared)
        id: setup-ffmpeg
        uses: ./
        with:
          ffmpeg-version: 'release'
          linking-type: shared

      - run: ffmpeg -version
      - run: ffprobe -version
      - run: dir ${{ steps.setup-ffmpeg.outputs.ffmpeg-path }}
